# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_inst_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrequencySettings(object):
    def setupUi(self, FrequencySettings):
        FrequencySettings.setObjectName("FrequencySettings")
        FrequencySettings.resize(709, 480)
        self.centralwidget = QtWidgets.QWidget(FrequencySettings)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    color: white;\n"
"    font-family: Nirmala UI;\n"
"    background-color: rgb(23,23,23);\n"
"}\n"
"\n"
"QFrame#frame{\n"
"    border-radius: 15px;\n"
"    border: 3px solid  qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(30, 11, 11, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(15, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_21 = QtWidgets.QFrame(self.frame_4)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        self.frame_24.setMinimumSize(QtCore.QSize(160, 160))
        self.frame_24.setMaximumSize(QtCore.QSize(160, 160))
        self.frame_24.setStyleSheet("QFrame{\n"
"    border-radius: 80px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 120, 250, 255));\n"
"    \n"
"    \n"
"    image: url(:/img/img/icons8-onda-sonora-100.png);\n"
"}\n"
"")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_10.addWidget(self.frame_24)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_21)
        self.frame_37 = QtWidgets.QFrame(self.frame_4)
        self.frame_37.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setMinimumSize(QtCore.QSize(228, 103))
        self.frame_38.setMaximumSize(QtCore.QSize(228, 103))
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_description_6 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_6.setFont(font)
        self.label_description_6.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_6.setObjectName("label_description_6")
        self.verticalLayout_29.addWidget(self.label_description_6)
        self.label_description_7 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_7.setFont(font)
        self.label_description_7.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_7.setObjectName("label_description_7")
        self.verticalLayout_29.addWidget(self.label_description_7)
        self.horizontalLayout_13.addWidget(self.frame_38)
        spacerItem4 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.frame_37)
        self.comboBox_instruments_list = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_instruments_list.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_instruments_list.setMaximumSize(QtCore.QSize(555, 40))
        self.comboBox_instruments_list.setToolTipDuration(5000)
        self.comboBox_instruments_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_instruments_list.setObjectName("comboBox_instruments_list")
        self.verticalLayout_2.addWidget(self.comboBox_instruments_list)
        self.pushButton_refresh_instrument = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_refresh_instrument.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_refresh_instrument.setMaximumSize(QtCore.QSize(555, 40))
        self.pushButton_refresh_instrument.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refresh_instrument.setToolTipDuration(5000)
        self.pushButton_refresh_instrument.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"color:#DCDCDC;\n"
"}")
        self.pushButton_refresh_instrument.setObjectName("pushButton_refresh_instrument")
        self.verticalLayout_2.addWidget(self.pushButton_refresh_instrument)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(20, 0, 0, 29)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setMinimumSize(QtCore.QSize(0, 31))
        self.label_43.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color:#DCDCDC;")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.verticalLayout.addWidget(self.label_43)
        self.frame_53 = QtWidgets.QFrame(self.frame_2)
        self.frame_53.setStyleSheet("QDoubleSpinBox{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font: 16px;\n"
"    padding: 10px;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-arriba-15.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button { \n"
"    border: none;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button { \n"
"    border: none;\n"
"}")
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_53)
        self.verticalLayout_37.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_37.setSpacing(9)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.frame_54 = QtWidgets.QFrame(self.frame_53)
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.frame_54)
        self.label_17.setMinimumSize(QtCore.QSize(180, 0))
        self.label_17.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.doubleSpinBox_FreqCenter = QtWidgets.QDoubleSpinBox(self.frame_54)
        self.doubleSpinBox_FreqCenter.setDecimals(3)
        self.doubleSpinBox_FreqCenter.setObjectName("doubleSpinBox_FreqCenter")
        self.horizontalLayout_22.addWidget(self.doubleSpinBox_FreqCenter)
        self.verticalLayout_37.addWidget(self.frame_54)
        self.frame_55 = QtWidgets.QFrame(self.frame_53)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_55)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.frame_55)
        self.label_18.setMinimumSize(QtCore.QSize(180, 0))
        self.label_18.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.doubleSpinBox_FreqStep = QtWidgets.QDoubleSpinBox(self.frame_55)
        self.doubleSpinBox_FreqStep.setDecimals(3)
        self.doubleSpinBox_FreqStep.setObjectName("doubleSpinBox_FreqStep")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_FreqStep)
        self.verticalLayout_37.addWidget(self.frame_55)
        self.frame_56 = QtWidgets.QFrame(self.frame_53)
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_56)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.frame_56)
        self.label_24.setMinimumSize(QtCore.QSize(180, 0))
        self.label_24.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.doubleSpinBox_FreqStart = QtWidgets.QDoubleSpinBox(self.frame_56)
        self.doubleSpinBox_FreqStart.setDecimals(3)
        self.doubleSpinBox_FreqStart.setObjectName("doubleSpinBox_FreqStart")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_FreqStart)
        self.verticalLayout_37.addWidget(self.frame_56)
        self.frame_57 = QtWidgets.QFrame(self.frame_53)
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_57)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(self.frame_57)
        self.label_25.setMinimumSize(QtCore.QSize(180, 0))
        self.label_25.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.doubleSpinBox_FreqStop = QtWidgets.QDoubleSpinBox(self.frame_57)
        self.doubleSpinBox_FreqStop.setDecimals(3)
        self.doubleSpinBox_FreqStop.setObjectName("doubleSpinBox_FreqStop")
        self.horizontalLayout_25.addWidget(self.doubleSpinBox_FreqStop)
        self.verticalLayout_37.addWidget(self.frame_57)
        self.verticalLayout.addWidget(self.frame_53)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.pushButton_SendSettings = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_SendSettings.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_SendSettings.setMaximumSize(QtCore.QSize(555, 40))
        self.pushButton_SendSettings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_SendSettings.setToolTipDuration(5000)
        self.pushButton_SendSettings.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    color: white;\n"
"    border: 1px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.pushButton_SendSettings.setObjectName("pushButton_SendSettings")
        self.verticalLayout.addWidget(self.pushButton_SendSettings)
        self.pushButton_CheckSettings = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_CheckSettings.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_CheckSettings.setMaximumSize(QtCore.QSize(555, 40))
        self.pushButton_CheckSettings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_CheckSettings.setToolTipDuration(5000)
        self.pushButton_CheckSettings.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(34,36,44);\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.pushButton_CheckSettings.setObjectName("pushButton_CheckSettings")
        self.verticalLayout.addWidget(self.pushButton_CheckSettings)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_close.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close.setToolTipDuration(5000)
        self.pushButton_close.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(23, 23, 25);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    image: url(:/icons/icons/icons8-eliminar-24.png);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 40, 38);\n"
"}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout_3.addWidget(self.pushButton_close)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame)
        FrequencySettings.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrequencySettings)
        QtCore.QMetaObject.connectSlotsByName(FrequencySettings)

    def retranslateUi(self, FrequencySettings):
        _translate = QtCore.QCoreApplication.translate
        FrequencySettings.setWindowTitle(_translate("FrequencySettings", "Frequency Settings"))
        self.label_description_6.setText(_translate("FrequencySettings", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">INSTRUMENT</span></p></body></html>"))
        self.label_description_7.setText(_translate("FrequencySettings", "<html><head/><body><p><span style=\" font-size:18pt;\">SETTINGS</span></p></body></html>"))
        self.comboBox_instruments_list.setToolTip(_translate("FrequencySettings", "Instruments list."))
        self.pushButton_refresh_instrument.setToolTip(_translate("FrequencySettings", "Refresh instruments list."))
        self.pushButton_refresh_instrument.setText(_translate("FrequencySettings", "REFRESH LIST"))
        self.label_43.setText(_translate("FrequencySettings", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">FREQUENCY </span><span style=\" font-size:14pt;\">SETTINGS:</span></p></body></html>"))
        self.label_17.setText(_translate("FrequencySettings", "FREQUENCY CENTER [MHz]:"))
        self.label_18.setText(_translate("FrequencySettings", "FREQUENCY STEP [MHz]:"))
        self.label_24.setText(_translate("FrequencySettings", "FREQUENCY START [MHz]:"))
        self.label_25.setText(_translate("FrequencySettings", "FREQUENCY STOP [MHz]:"))
        self.pushButton_SendSettings.setToolTip(_translate("FrequencySettings", "<html><head/><body><p><span style=\" font-weight:600;\">Send</span> settings</p></body></html>"))
        self.pushButton_SendSettings.setText(_translate("FrequencySettings", "SEND"))
        self.pushButton_CheckSettings.setToolTip(_translate("FrequencySettings", "Refresh instruments list."))
        self.pushButton_CheckSettings.setText(_translate("FrequencySettings", "CHECK SETTINGS"))
        self.pushButton_close.setToolTip(_translate("FrequencySettings", "<html><head/><body><p><span style=\" font-weight:600;\">Close</span> Window</p></body></html>"))
import resources_rc
