# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_proyecto.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1666, 1018)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    color: white;\n"
"    font-family: Nirmala UI;\n"
"    background-color: rgb(23,23,23);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, -1, 35, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setMinimumSize(QtCore.QSize(359, 0))
        self.frame_19.setMaximumSize(QtCore.QSize(359, 16777215))
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_25 = QtWidgets.QFrame(self.frame_19)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_35 = QtWidgets.QFrame(self.frame_25)
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setMinimumSize(QtCore.QSize(228, 103))
        self.frame_36.setMaximumSize(QtCore.QSize(228, 103))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_description_6 = QtWidgets.QLabel(self.frame_36)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_6.setFont(font)
        self.label_description_6.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_6.setObjectName("label_description_6")
        self.verticalLayout_26.addWidget(self.label_description_6)
        self.label_description_7 = QtWidgets.QLabel(self.frame_36)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_7.setFont(font)
        self.label_description_7.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_7.setObjectName("label_description_7")
        self.verticalLayout_26.addWidget(self.label_description_7)
        self.horizontalLayout_13.addWidget(self.frame_36)
        spacerItem1 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_15.addWidget(self.frame_35)
        self.frame_18 = QtWidgets.QFrame(self.frame_25)
        self.frame_18.setMinimumSize(QtCore.QSize(311, 270))
        self.frame_18.setMaximumSize(QtCore.QSize(311, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_10.setContentsMargins(20, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_14 = QtWidgets.QFrame(self.frame_18)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_14)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.frame_12)
        self.label_11.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.comboBox_port_list = QtWidgets.QComboBox(self.frame_12)
        self.comboBox_port_list.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_port_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_port_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_port_list.setObjectName("comboBox_port_list")
        self.horizontalLayout_5.addWidget(self.comboBox_port_list)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_14)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_baudrate.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_baudrate.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_baudrate.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_6.addWidget(self.comboBox_baudrate)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.verticalLayout_10.addWidget(self.frame_14)
        self.pushButton_connect = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_connect.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_connect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_connect.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    color: white;\n"
"    border: 1px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout_10.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_disconnect.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_disconnect.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_disconnect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_disconnect.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    color: white;\n"
"    border: 1px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout_10.addWidget(self.pushButton_disconnect)
        self.pushButton_refresh_port = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_refresh_port.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_refresh_port.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_refresh_port.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refresh_port.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"color:#DCDCDC;\n"
"}")
        self.pushButton_refresh_port.setObjectName("pushButton_refresh_port")
        self.verticalLayout_10.addWidget(self.pushButton_refresh_port)
        self.verticalLayout_15.addWidget(self.frame_18)
        self.label_status = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("border: none;\n"
"padding-right: 25px;")
        self.label_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_15.addWidget(self.label_status)
        self.frame_37 = QtWidgets.QFrame(self.frame_25)
        self.frame_37.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setMinimumSize(QtCore.QSize(228, 103))
        self.frame_38.setMaximumSize(QtCore.QSize(228, 103))
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_description_8 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_8.setFont(font)
        self.label_description_8.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_8.setObjectName("label_description_8")
        self.verticalLayout_29.addWidget(self.label_description_8)
        self.label_description_9 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_9.setFont(font)
        self.label_description_9.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_9.setObjectName("label_description_9")
        self.verticalLayout_29.addWidget(self.label_description_9)
        self.horizontalLayout_14.addWidget(self.frame_38)
        spacerItem3 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.verticalLayout_15.addWidget(self.frame_37)
        self.frame_39 = QtWidgets.QFrame(self.frame_25)
        self.frame_39.setMinimumSize(QtCore.QSize(0, 160))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_30.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.comboBox_instruments_list = QtWidgets.QComboBox(self.frame_39)
        self.comboBox_instruments_list.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_instruments_list.setMaximumSize(QtCore.QSize(555, 40))
        self.comboBox_instruments_list.setToolTipDuration(5000)
        self.comboBox_instruments_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    \n"
"    image: url(:/icons/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_instruments_list.setObjectName("comboBox_instruments_list")
        self.verticalLayout_30.addWidget(self.comboBox_instruments_list)
        self.pushButton_refresh_instrument = QtWidgets.QPushButton(self.frame_39)
        self.pushButton_refresh_instrument.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_refresh_instrument.setMaximumSize(QtCore.QSize(555, 40))
        self.pushButton_refresh_instrument.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refresh_instrument.setToolTipDuration(5000)
        self.pushButton_refresh_instrument.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"color:#DCDCDC;\n"
"}")
        self.pushButton_refresh_instrument.setObjectName("pushButton_refresh_instrument")
        self.verticalLayout_30.addWidget(self.pushButton_refresh_instrument)
        self.frame_16 = QtWidgets.QFrame(self.frame_39)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.pushButton_inst_settings = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_inst_settings.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_inst_settings.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_inst_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_inst_settings.setToolTipDuration(5000)
        self.pushButton_inst_settings.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"    \n"
"    image: url(:/icons/icons/icons8-ajustes-25.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.pushButton_inst_settings.setText("")
        self.pushButton_inst_settings.setObjectName("pushButton_inst_settings")
        self.horizontalLayout_15.addWidget(self.pushButton_inst_settings)
        self.verticalLayout_30.addWidget(self.frame_16)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem5)
        self.verticalLayout_15.addWidget(self.frame_39)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.frame_3 = QtWidgets.QFrame(self.frame_25)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(11, 11, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_description_2 = QtWidgets.QLabel(self.frame_5)
        self.label_description_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_2.setFont(font)
        self.label_description_2.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_2.setObjectName("label_description_2")
        self.verticalLayout_4.addWidget(self.label_description_2)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem7 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(-1, 11, -1, 0)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_go_home = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_go_home.setMinimumSize(QtCore.QSize(196, 40))
        self.pushButton_go_home.setMaximumSize(QtCore.QSize(1500, 40))
        self.pushButton_go_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_go_home.setAutoFillBackground(False)
        self.pushButton_go_home.setStyleSheet("")
        self.pushButton_go_home.setObjectName("pushButton_go_home")
        self.horizontalLayout_10.addWidget(self.pushButton_go_home)
        self.horizontalLayout_9.addWidget(self.frame_10)
        spacerItem8 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_Z_position = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_Z_position.setMinimumSize(QtCore.QSize(147, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_Z_position.setFont(font)
        self.lineEdit_Z_position.setStyleSheet("QLineEdit{\n"
"    color:  rgba(71, 129, 255, 255);\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.lineEdit_Z_position.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Z_position.setObjectName("lineEdit_Z_position")
        self.horizontalLayout_3.addWidget(self.lineEdit_Z_position)
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.pushButton_Go = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Go.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_Go.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_Go.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Go.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"    \n"
"    image: url(:/icons/icons/icons8-lleno-enviado-25.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.pushButton_Go.setText("")
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.horizontalLayout_2.addWidget(self.pushButton_Go)
        spacerItem10 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_15.addWidget(self.frame_3)
        self.verticalLayout_14.addWidget(self.frame_25)
        self.horizontalLayout.addWidget(self.frame_19)
        self.frame_31 = QtWidgets.QFrame(self.frame)
        self.frame_31.setMinimumSize(QtCore.QSize(359, 0))
        self.frame_31.setMaximumSize(QtCore.QSize(359, 16777215))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_23.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_32 = QtWidgets.QFrame(self.frame_31)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem11 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setMinimumSize(QtCore.QSize(228, 103))
        self.frame_33.setMaximumSize(QtCore.QSize(228, 103))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_description_4 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_4.setFont(font)
        self.label_description_4.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_4.setObjectName("label_description_4")
        self.verticalLayout_24.addWidget(self.label_description_4)
        self.label_description_5 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description_5.setFont(font)
        self.label_description_5.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description_5.setObjectName("label_description_5")
        self.verticalLayout_24.addWidget(self.label_description_5)
        self.horizontalLayout_11.addWidget(self.frame_33)
        spacerItem12 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_23.addWidget(self.frame_32)
        self.frame_34 = QtWidgets.QFrame(self.frame_31)
        self.frame_34.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_34.setStyleSheet("QFrame{\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.plainTextEdit_CodeView = QtWidgets.QPlainTextEdit(self.frame_34)
        self.plainTextEdit_CodeView.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.plainTextEdit_CodeView.setStyleSheet("QPlainTextEdit{\n"
"    border: None;\n"
"    background-color: transparent;\n"
"    font-size: 18px;\n"
"}")
        self.plainTextEdit_CodeView.setObjectName("plainTextEdit_CodeView")
        self.verticalLayout_25.addWidget(self.plainTextEdit_CodeView)
        self.verticalLayout_23.addWidget(self.frame_34)
        self.frame_15 = QtWidgets.QFrame(self.frame_31)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_Open = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_Open.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Open.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_Open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Open.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    color: white;\n"
"    border: 1px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout_12.addWidget(self.pushButton_Open)
        self.verticalLayout_23.addWidget(self.frame_15)
        self.progressBar = QtWidgets.QProgressBar(self.frame_31)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(34,36,44);\n"
"    color: rgb(200,200,200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_23.addWidget(self.progressBar)
        self.label_state = QtWidgets.QLabel(self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.label_state.setFont(font)
        self.label_state.setStyleSheet("border: none;")
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.verticalLayout_23.addWidget(self.label_state)
        self.frame_2 = QtWidgets.QFrame(self.frame_31)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_23.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame_31)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(20, 25, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_description = QtWidgets.QLabel(self.frame_4)
        self.label_description.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_2.addWidget(self.label_description)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.frame_7)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, 7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_22)
        self.tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"color:#DCDCDC;\n"
"background-color: rgba(255,255,255,20);\n"
"border:none;\n"
"border-radius: 0px;\n"
"alternate-background-color: rgba(100, 200, 255, 25);\n"
"gridline-color:#242424;\n"
"}\n"
" \n"
"QTableWidget::item:selected{\n"
"color:#DCDCDC;\n"
"\n"
"}\n"
" \n"
"QTableWidget::item:hover{\n"
"background:rgba(71, 129, 255, 255);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"color:#DCDCDC;\n"
"font: bold;\n"
"font-size: 18px;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"background: rgba(71, 129, 255, 255);\n"
"padding:3px;\n"
"margin:0px;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_8.addWidget(self.tableWidget)
        self.verticalLayout_13.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_7)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_23.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_Start = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(130, 40))
        self.pushButton_Start.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_Start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Start.setToolTipDuration(5000)
        self.pushButton_Start.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/icons/icons8-eliminar-25.png);\n"
"}")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout_7.addWidget(self.pushButton_Start)
        self.pushButton_pause = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_pause.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_pause.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pause.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"    image: url(:/icons/icons/icons8-pausa-25.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.pushButton_pause.setText("")
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_7.addWidget(self.pushButton_pause)
        self.pushButton_stop = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border: none;\n"
"    background-color: rgb(34,36,44);\n"
"    image: url(:/icons/icons/icons8-detener-26.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(44,46,54);\n"
"}")
        self.pushButton_stop.setText("")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout_7.addWidget(self.pushButton_stop)
        spacerItem13 = QtWidgets.QSpacerItem(375, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.pushButton_clean = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clean.setStyleSheet("image: url(:/icons/icons/icons8-escoba-25.png);")
        self.pushButton_clean.setText("")
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.horizontalLayout_7.addWidget(self.pushButton_clean)
        self.pushButton_Export = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_Export.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_Export.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_Export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Export.setToolTipDuration(5000)
        self.pushButton_Export.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/icons/icons8-lleno-enviado-25.png);\n"
"}")
        self.pushButton_Export.setObjectName("pushButton_Export")
        self.horizontalLayout_7.addWidget(self.pushButton_Export)
        self.verticalLayout_13.addWidget(self.frame_23)
        self.label_credits = QtWidgets.QLabel(self.frame_7)
        self.label_credits.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color:  rgba(71, 129, 255, 255);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_13.addWidget(self.label_credits)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_description_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">SERIAL PORT</span></p></body></html>"))
        self.label_description_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">SETTINGS</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "PORT NAME:"))
        self.label_12.setText(_translate("MainWindow", "BAUDRATE:"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "DISCONNECT"))
        self.pushButton_refresh_port.setText(_translate("MainWindow", "REFRESH PORT LIST"))
        self.label_status.setText(_translate("MainWindow", "Disconnected"))
        self.label_description_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">INSTRUMENT</span></p></body></html>"))
        self.label_description_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">SETTINGS</span></p></body></html>"))
        self.comboBox_instruments_list.setToolTip(_translate("MainWindow", "Instruments list."))
        self.pushButton_refresh_instrument.setToolTip(_translate("MainWindow", "Refresh instruments list."))
        self.pushButton_refresh_instrument.setText(_translate("MainWindow", "REFRESH LIST"))
        self.pushButton_inst_settings.setToolTip(_translate("MainWindow", "<html><head/><body><p>Settings <span style=\" font-weight:600;\">Spectrum Analyzer.</span></p></body></html>"))
        self.label_description_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">HEIGHT</span><span style=\" font-size:16pt;\"> ADJUST</span></p></body></html>"))
        self.pushButton_go_home.setText(_translate("MainWindow", "GO HOME"))
        self.lineEdit_Z_position.setPlaceholderText(_translate("MainWindow", "X.XXX"))
        self.label_description_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">G-CODE</span></p></body></html>"))
        self.label_description_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">FILE VIEWER</span></p></body></html>"))
        self.pushButton_Open.setText(_translate("MainWindow", "OPEN FILE"))
        self.label_state.setText(_translate("MainWindow", "In process..."))
        self.label_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">MEASUREMENT</span><span style=\" font-size:18pt; font-weight:600;\"> DATA</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X [mm]"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y [mm]"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z [mm]"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MK1 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MK1 - Amp. [dBuV]"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "MK2 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "MK2 - Amp. [dBuV]"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "MK3 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "MK2 - Amp. [dBuV]"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "MK4 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "MK4 - Amp. [dBuV]"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "MK5 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "MK5 - Amp. [dBuV]"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "MK6 - Freq. [Hz]"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "MK6 - Amp. [dBuV]"))
        self.pushButton_Start.setToolTip(_translate("MainWindow", "Clean Terminal."))
        self.pushButton_Start.setText(_translate("MainWindow", "START MEASURE"))
        self.pushButton_Export.setToolTip(_translate("MainWindow", "Send data"))
        self.pushButton_Export.setText(_translate("MainWindow", "EXPORT"))
        self.label_credits.setText(_translate("MainWindow", "<strong>Created</strong> by Joaquin Allione"))
import resources_rc
